- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/CompilerTest.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/XbaseCompiler.java
> [493900] fixed array list literal handling in xbase compiler

- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/resources/ResourceStorageTest.xtend
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/resources/ResourceStorageTest.java
Integ test for https://github.com/eclipse/xtext-core/issues/65
> Integration Test for Core Issue 65

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/jvmmodel/IJvmModelAssociations.java
> [493785] getPrimaryJvmElement fix javadoc

- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/ecore/EMFGeneratorFragment.java
> [431435] Bind generated EPackage and EFactory

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/XbaseValidator.java
> [#50] checkCasts: Add NPE guard

- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/validation/FeatureCallValidationTest.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/FeatureLinkingCandidate.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/XbaseConfigurableIssueCodes.java
[476779][validation] Make validation of non-static access to static member configurable
> [476779][validation] Make validation of non-static access to static member configurable

- org.eclipse.xtext.common.types.tests/.classpath
- org.eclipse.xtext.common.types.tests/build.gradle
- org.eclipse.xtext.common.types.tests/testdata/testdata/Outer.java
- org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/access/impl/IndexedJvmTypeAccessTest.java
- org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/access/impl/InnerClassNameVariantsTest.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/impl/IndexedJvmTypeAccess.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/impl/InnerClassNameVariants.java
fix for inner class issue in IndexedJvmTypeAccess + ASM. Fixes #30
> fix for inner class issue in IndexedJvmTypeAccess + ASM. Fixes #30

- gradle/eclipse-project-layout.gradle
- gradle/java-compiler-settings.gradle
- org.eclipse.xtext.common.types.tests/build.gradle
- org.eclipse.xtext.extras.tests/build.gradle
- org.eclipse.xtext.java.tests/build.gradle
- org.eclipse.xtext.smap/build.gradle
Consistent use of tabs instead of spaces
Use single whitespace between brackets
> [format] Streamlined whitespaces

- org.eclipse.xtext.builder.standalone.tests/.classpath
- org.eclipse.xtext.common.types.tests/.classpath
- org.eclipse.xtext.common.types/.classpath
- org.eclipse.xtext.extras.tests/.classpath
- org.eclipse.xtext.generator/.classpath
- org.eclipse.xtext.purexbase.tests/.classpath
- org.eclipse.xtext.purexbase/.classpath
- org.eclipse.xtext.xbase.ide/.classpath
- org.eclipse.xtext.xbase.testlanguages/.classpath
- org.eclipse.xtext.xbase/.classpath
> [#55] Ignore optional compile problems on *-gen source folders

- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
> [502879] Streamlined plugin metadata

- org.eclipse.xtext.builder.standalone/build.gradle
added dependencies to xbase and jdt to fix generated pom
Fixes #22
> added dependencies to xbase and jdt to fix generated pom

- org.eclipse.xtext.common.types.tests/.classpath
- org.eclipse.xtext.xbase.ide/src/org/eclipse/xtext/xbase/ide/DefaultXbaseIdeModule.xtend
- org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/DefaultXbaseIdeModule.java
See eclipse/xtext-core#127 and eclipse/xtext-web#6.
> Created DefaultXbaseIdeModule

- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/xtext/AbstractProjectAwareResourceDescriptionsProvider.java
> Typo in @since annotation fixed

- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/controlflow/ConstantConditionsInterpreter.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/interpreter/AbstractConstantExpressionsInterpreter.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/lib/ArithmeticExtensionGenerator.java
> [501975] Null guard for switch statements

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/XbaseValidator.java
Covered by XtendValidationTest, see https://github.com/eclipse/xtext-xtend/pull/27
Signed-off-by: Karsten Thoms karsten.thoms@itemis.de
> [381031] Detect recursive calls of private methods

- org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/test/CompilerTest.xtend
- org.eclipse.xtext.purexbase.tests/xtend-gen/org/eclipse/xtext/purexbase/test/CompilerTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/CompilerTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/CompilerTests2.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/NewLanguageFeaturesCompilerTest.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/output/CompilerTraceTest.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/compiler/CompilerTests2.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/compiler/NewLanguageFeaturesCompilerTest.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/FeatureCallCompiler.java
This PR will tweak the FeatureCallCompiler to avoid declaration of unnecessary variables. It will make the compiled code more compact and often more readable. Test expectations are adjusted.
> [492072] Optimize FeatureCallCompiler

- org.eclipse.xtext.generator/src/org/eclipse/xtext/ui/generator/compare/CompareFragment.java
[415677] Language Specific Compare Viewer title (old generator)
> [415677] Language Specific Compare Viewer title

- gradle/developers.gradle
> fixed invalid developers.gradle. resolves #109

- org.eclipse.xtext.purexbase.ide/about.html
- org.eclipse.xtext.purexbase.ide/build.properties
> added about.html #120

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/override/IOverrideCheckResult.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/override/LazyOverrideCheckResult.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/override/OverrideTester.java
[418504] Override Tester: Check for Synchronized
> [418504] Override Tester: Check for Synchronized

- gradle/eclipse-project-layout.gradle
> delete ecore after test

- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/formatting/XbaseFormatterTest.xtend
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/formatting/XbaseFormatterTest.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.xtend
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.java
[474022] Indent Try Catch Finally on Var Decls
> [474022] Indent Try Catch Finally on Var Decls

- org.eclipse.xtext.xbase.testlanguages/model/generated/Bug462047Lang.genmodel
- org.eclipse.xtext.xbase.testlanguages/model/generated/ContentAssistFragmentTestLang.genmodel
- org.eclipse.xtext.xbase.testlanguages/model/generated/XImportSectionTestLang.genmodel
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/AbstractContentAssistFragmentTestLangRuntimeModule.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/AbstractXImportSectionTestLangRuntimeModule.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/ContentAssistFragmentTestLangStandaloneSetupGenerated.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/XImportSectionTestLangStandaloneSetupGenerated.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/bug462047/AbstractBug462047LangRuntimeModule.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/bug462047/Bug462047LangStandaloneSetupGenerated.java
- org.eclipse.xtext.xbase.testlanguages/src/org/eclipse/xtext/xbase/testlanguages/GenerateXbaseTestLanguages.mwe2
> fixed broken test languages (missing file extensions) #137

- org.eclipse.xtext.xbase.testdata/src/closures/IAcceptors.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/CompilerTest.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/XbaseCompiler.java
[472265] [xbase][compiler] SAM methods with varargs are not compiled as such
> [472265] [xbase][compiler] SAM methods with varargs are not compiled as such

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/AbstractXbaseCompiler.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/FeatureCallCompiler.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/LiteralsCompiler.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/XbaseCompiler.java
[516321]  Xtend 2.11 compiles 'forever'
> [516321]  Xtend 2.11 compiles 'forever'

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/Xbase.xtext
Added Override annotation to Xbase/QualifiedName to avoid compiler warning.
> Added missing @Override

- org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/util/DeprecationUtilTest.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/util/DeprecationUtil.java
- org.eclipse.xtext.xbase.ide/src/org/eclipse/xtext/xbase/ide/highlighting/XbaseHighlightingCalculator.java
- org.eclipse.xtext.xbase.testdata/src/org/eclipse/xtext/common/types/util/Deprecation2.java
[409297][hightlighting][deprecation] Semantics different from JDTs
> [409297][hightlighting][deprecation] Semantics different from JDTs

- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/junit/evaluation/AbstractXbaseEvaluationTest.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/NumberLiterals.java
> Fixed potential compilation problem with number literals

- .project
- org.eclipse.xtext.builder.standalone.tests/.project
- org.eclipse.xtext.builder.standalone/.project
- org.eclipse.xtext.common.types.tests/.project
- org.eclipse.xtext.common.types/.project
- org.eclipse.xtext.ecore/.project
- org.eclipse.xtext.extras.tests/.project
- org.eclipse.xtext.generator/.project
- org.eclipse.xtext.java.tests/.project
- org.eclipse.xtext.java/.project
- org.eclipse.xtext.purexbase.ide/.project
- org.eclipse.xtext.purexbase.tests/.project
- org.eclipse.xtext.purexbase/.project
- org.eclipse.xtext.smap/.project
- org.eclipse.xtext.xbase.ide/.project
- org.eclipse.xtext.xbase.testdata/.project
- org.eclipse.xtext.xbase.testing/.project
- org.eclipse.xtext.xbase.testlanguages/.project
- org.eclipse.xtext.xbase.tests/.project
- org.eclipse.xtext.xbase/.project
> gradleprojectbuilder added by Buildship project import

- org.eclipse.xtext.xbase.testdata/src/testdata/AssertJLikeAssertions.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/junit/evaluation/AbstractXbaseEvaluationTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/linking/AbstractXbaseLinkingTest.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/conformance/RawTypeConformanceComputer.java
> [485032] Fixed issue with Wildcard Ref and Primitive types

- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/jvmmodel/JvmModelAssociatorTest.xtend
- org.eclipse.xtext.xbase.tests/suites/org/eclipse/xtext/xbase/tests/jvmmodel/JvmModelSuite.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/jvmmodel/JvmModelAssociatorTest.java
> Renamed JvmModelAssociaterTest -> JvmModelAssociatorTest

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/DefaultXbaseRuntimeModule.java
[490371] [xbase] Bind JvmModelTargetURICollector by default for all xbase languages
> [490371] [xbase] Bind JvmModelTargetURICollector by default for all xbase languages

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/imports/TypeUsageCollector.java
Field might not been initialized when evaluating the condition
> [521819] Added null guard for field currentThisType

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/FeatureCallCompiler.java
> fixed declaration of inline annotation in xtend #256

- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/AbstractOutputComparingCompilerTests.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/CompilerTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/imports/DefaultImportsConfigurationTest.xtend
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/imports/DefaultImportsConfigurationTest.java
> fixed tests failing on windows

- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/AbstractPortableURIsTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/URIsInEcoreFilesTest.java
> URIsInEcoreFilesTest fails in Eclipse #26

- org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/OnTheFlyJavaCompiler.java
removed patchedfilesystem from OnTheFlyJavaCompiler to avoid problems with oxygen 1a
https://github.com/eclipse/xtext-eclipse/issues/393
> removed patchedfilesystem from OnTheFlyJavaCompiler to avoid problems with oxygen 1a

- gradle/versions.gradle
- org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/p2/category.xml
- releng/p2/pom.xml
- releng/pom.xml
- releng/releng-target/pom.xml
> increased versions to 2.14

- org.eclipse.xtext.xbase.testlanguages.ide/.classpath
> [eclipse/xtext#1129] Automatic changes by Buildship

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/IssueCodes.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/XbaseConfigurableIssueCodes.java
moved 'copy java problems' configurable issue code to xtext core 
https://github.com/eclipse/xtext-core/issues/544
> moved 'copy java problems' configurable issue code to xtext core

- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/XbaseQualifiedNameConverterTest.xtend
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/XbaseQualifiedNameConverterTest.java
> Added test for XbaseQualifiedNameConverter

- org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/adapter/Generator2AdapterSetup.java
- org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/parser/antlr/AbstractAntlrXtendGeneratorFragment.java
- org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/serializer/SerializerFragment.java
> regenerated xtend code (java 9 java.lang.Module conflict)

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/jvmmodel/JvmModelCompleter.java
[#207] added mitigation for missing @Generated annotation in Java 9
> [#207] added mitigation for missing @Generated annotation in Java 9

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/ImportManager.java
For enabling overriding of the import manager, the internal fields of ImportManager should be accessible.
> Add protected accessors to ImportManager.

- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/AbstractOutputComparingCompilerTests.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/CompilerTests2.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/output/CompilerTraceTest.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/compiler/CompilerTests2.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/XbaseCompiler.java
Add test cases for new code generation cases.
Change-Id: Ia3becba790b2cad6f8c874d750d443609aa2e956
Signed-off-by: Arne Deutsch <arne@idedeluxe.com>
> [Bug 420984] Adapted compiler to generate only used variables.

- org.eclipse.xtext.builder.standalone/xtend-gen/org/eclipse/xtext/builder/standalone/StandaloneBuilder.java
- org.eclipse.xtext.builder.standalone/xtend-gen/org/eclipse/xtext/builder/standalone/incremental/ResourceURICollector.java
- org.eclipse.xtext.java/xtend-gen/org/eclipse/xtext/java/resource/JavaDerivedStateComputer.java
- org.eclipse.xtext.java/xtend-gen/org/eclipse/xtext/java/resource/JavaResource.java
- org.eclipse.xtext.java/xtend-gen/org/eclipse/xtext/java/resource/JavaResourceServiceProvider.java
- org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/types/ClasspathScanner.java
- org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/types/ClasspathTypeDescriptor.java
- org.eclipse.xtext.xbase.testing/xtend-gen/org/eclipse/xtext/xbase/testing/InMemoryJavaCompiler.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/jvmmodel/JvmTypeReferenceBuilderTest.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/TypeResolutionCancelTest.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/annotations/validation/AnnotationValueValidator.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/compiler/ErrorSafeExtensions.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/compiler/JvmModelGenerator.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/controlflow/ConstantConditionsInterpreter.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/controlflow/EarlyExitInterpreter.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/util/XSwitchExpressions.java
> [420984] Compiler optimization: Suppress unused exception variable

- org.eclipse.xtext.common.types.tests/build.gradle
- org.eclipse.xtext.java.tests/build.gradle
added error prone to test dependencies (req. by guava 21)
> added error prone to test dependencies (req. by guava 21)

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/scoping/batch/FeatureScopeSessionWithContext.java
> [#229] Fixed Visibility issues with nested types

- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/JvmModelGeneratorTest.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/jvmmodel/TypeSignatureHashTest.xtend
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/compiler/JvmModelGeneratorTest.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/jvmmodel/TypeSignatureHashTest.java
> get rid of deprecated code

- org.eclipse.xtext.common.types/xtend-gen/org/eclipse/xtext/common/types/descriptions/TypeResourceDescription.java
- org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/types/ClasspathTypeDescriptor.java
- org.eclipse.xtext.xbase.testing/xtend-gen/org/eclipse/xtext/xbase/testing/JavaSource.java
- org.eclipse.xtext.xbase.testing/xtend-gen/org/eclipse/xtext/xbase/testing/RegisteringFileSystemAccess.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/controlflow/BooleanResult.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/controlflow/EvaluationResult.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/controlflow/ThisReference.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting/CommentInfo.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting/FormattingData.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting/HiddenLeafs.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting/LeafInfo.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting/NewLineData.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting/TextReplacement.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting/WhitespaceData.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting/WhitespaceInfo.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/interpreter/Context.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/scoping/batch/ExpressionBucket.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/scoping/batch/SynonymTypeBucket.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/scoping/batch/TypeBucket.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/scoping/batch/TypeReferenceBucket.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/scoping/batch/TypeWithRestrictedNamesBucket.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/typesystem/references/LightweightBoundTypeArgument.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/typesystem/references/LightweightMergedBoundTypeArgument.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/typesystem/references/LightweightTraversalData.java
Regenerated against lastest xbase-lib
https://github.com/eclipse/xtext/issues/1174
> Regenerated against lastest xbase-lib

- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/JvmTypeChangeDispatcher.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/XbaseDiagnostician.java
> [eclipse/xtext-core#449] Avoid stack overflow with deep EMF containment

- org.eclipse.xtext.java/src/org/eclipse/xtext/java/resource/JavaDerivedStateComputer.xtend
- org.eclipse.xtext.java/xtend-gen/org/eclipse/xtext/java/resource/JavaDerivedStateComputer.java
> fixed wrong j9 constant

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/imports/ConflictResolver.java
See https://github.com/eclipse/xtext-xtend/issues/403
> [#403] Fix failing ImportOrganizerTest test cases in Xtend repository.

- org.eclipse.xtext.extras.tests/src/org/eclipse/xtext/resource/uriHell/URIHandlerTest.xtend
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/adapter/Generator2AdapterSetup.xtend
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/AntlrGrammarComparator.xtend
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/XtextAntlrGeneratorComparisonFragment.xtend
- org.eclipse.xtext.java/src/org/eclipse/xtext/java/resource/JavaResource.xtend
- org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/InMemoryJavaCompiler.xtend
- org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/typesystem/PublicTypesForTesting.xtend
- org.eclipse.xtext.xbase.tests/longrunning/src/org/eclipse/xtext/xbase/tests/typesystem/InvariantTypeRecomputation.xtend
- org.eclipse.xtext.xbase.tests/longrunning/src/org/eclipse/xtext/xbase/tests/typesystem/TestingTypeResolvers.xtend
- org.eclipse.xtext.xbase.tests/longrunning/src/org/eclipse/xtext/xbase/tests/typesystem/ValidatingTypeComputation.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/junit/typesystem/PublicTypesForTesting.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/CompilationTestHelperTest.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/output/ErrorTreeAppendableTest.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/jvmmodel/JvmModelAssociatorTest.xtend
- org.eclipse.xtext.xbase/deprecated/org/eclipse/xtext/xbase/formatting/FormattableDocument.xtend
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/GeneratorConfigProvider.xtend
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/imports/ImportsAcceptor.xtend
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/resource/BatchLinkableResourceStorageWritable.xtend
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/resource/JvmElementAtOffsetHelper.xtend
Signed-off-by: Titouan Vervack <titouan.vervack@sigasi.com>
> Removed redundant modifiers

- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/ecore/EMFGeneratorFragment.java
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/XtextAntlrGeneratorComparisonFragment.xtend
- org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/parser/antlr/XtextAntlrGeneratorComparisonFragment.java
- org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/xbase/junit/evaluation/AbstractXbaseEvaluationTest.java
- org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/evaluation/AbstractXbaseEvaluationTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/junit/evaluation/AbstractXbaseEvaluationTest.java
- org.eclipse.xtext.xbase/deprecated/org/eclipse/xtext/xbase/formatting/FormattableDocument.xtend
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/controlflow/ConstantConditionsInterpreter.xtend
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/interpreter/AbstractConstantExpressionsInterpreter.xtend
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/DefaultReentrantTypeResolver.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/controlflow/ConstantConditionsInterpreter.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting/FormattableDocument.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/interpreter/ConstantExpressionEvaluationException.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/interpreter/StackedConstantExpressionEvaluationException.java
Signed-off-by: Titouan Vervack <titouan.vervack@sigasi.com>
> Fixed warnings

- gradle/versions.gradle
- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1178] bootstrap against 2.14
> [eclipse/xtext#1178] bootstrap against 2.14

- gradle/p2-deployment.gradle
- releng/releng-target/xtext-extras.target.target
> updated orbit to photon release

- org.eclipse.xtext.builder.standalone/build.gradle
- org.eclipse.xtext.common.types.tests/build.gradle
- org.eclipse.xtext.generator/build.gradle
- org.eclipse.xtext.java/build.gradle
- org.eclipse.xtext.purexbase.tests/build.gradle
- org.eclipse.xtext.xbase.testing/build.gradle
- org.eclipse.xtext.xbase.tests/build.gradle
[eclipse/xtext#1231] more precise exclusions
> [eclipse/xtext#1231] more precise exclusions

- gradle/p2-deployment.gradle
- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1168] set minimal target to oxygen
> [eclipse/xtext#1168] set minimal target to oxygen

- org.eclipse.xtext.purexbase/xtend-gen/org/eclipse/xtext/purexbase/formatting2/PureXbaseFormatter.java
- org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/contentassist/XbaseIdeContentProposalProvider.java
> regenerated against latest xtend

- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/ecore/EcoreGeneratorFragment.java
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/XtextAntlrGeneratorComparisonFragment.xtend
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/ex/rt/AntlrGeneratorFragment.java
- org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/parser/antlr/XtextAntlrGeneratorComparisonFragment.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/IFeatureScopeTracker.java
> fixed broken javadoc

- org.eclipse.xtext.common.types/.classpath
- org.eclipse.xtext.xbase.testing/.classpath
> [eclipse/xtext#1247] including attribute added for classpathentry

- org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/TemporaryFolder.java
> fixed javadoc warnings

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/imports/ImportOrganizer.java
> [eclipse/xtext-xtend#536] Do not add static import if extension import

- gradle/versions.gradle
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF_gen
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/types/TypesGeneratorFragment.java
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
[eclipse/xtext#1266] Update to ASM 6.2
> [eclipse/xtext#1266] Update to ASM 6.2

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/UniqueClassNameValidator.xtend
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/validation/UniqueClassNameValidator.java
> Bogus behavior of (ProjectAware)UniqueClassNameValidator #675

- gradle/versions.gradle
- org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/p2/category.xml
- releng/p2/pom.xml
- releng/pom.xml
- releng/releng-target/pom.xml
> updated versions to 2.16.0

- org.eclipse.xtext.builder.standalone/xtend-gen/org/eclipse/xtext/builder/standalone/StandaloneBuilder.java
- org.eclipse.xtext.builder.standalone/xtend-gen/org/eclipse/xtext/builder/standalone/incremental/ResourceURICollector.java
- org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/adapter/StringConcatOutputImpl.java
- org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/parser/antlr/AntlrGrammarComparator.java
- org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/parser/antlr/XtextAntlrGeneratorComparisonFragment.java
- org.eclipse.xtext.java/xtend-gen/org/eclipse/xtext/java/resource/ClassFileCache.java
- org.eclipse.xtext.java/xtend-gen/org/eclipse/xtext/java/resource/JavaDerivedStateComputer.java
- org.eclipse.xtext.java/xtend-gen/org/eclipse/xtext/java/resource/JavaResource.java
- org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/DefaultXbaseIdeModule.java
- org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/contentassist/TypeFilters.java
- org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/highlighting/XbaseHighlightingStyles.java
- org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/types/ClasspathScanner.java
- org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/types/ClasspathTypeDescriptor.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/ResolvedFeaturesTest.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/annotations/validation/UnresolvedFeatureCallTypeAwareMessageProvider.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/controlflow/EvaluationResult.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting/BasicFormatterPreferenceKeys.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting/FormattableDocument.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting/XbaseFormatterPreferenceKeys.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting2/XbaseFormatterPreferenceKeys.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/resource/BatchLinkableResourceStorageWritable.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/validation/ReadAndWriteTracking.java
Order of static & final modifiers changed
(eclipse/xtext-xtend#554)
> [eclipse/xtext#1272] Compile with Xtend 2.15

- gradle/p2-deployment.gradle
- gradle/versions.gradle
- releng/releng-target/xtext-extras.target.target
> [eclipse/xtext#1272] Set Xtext bootstrap 2.15

- gradle/bootstrap-setup.gradle
> [eclipse/xtext#1272] Remove signature workaround

- releng/pom.xml
Added property ‚upstreamBranch‘ which is considered by adjustPipelines.sh script
> [eclipse/xtext-umbrella#65] Adjust upstream branch

- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/BinaryClass.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/impl/JvmCompoundTypeReferenceImplCustom.java
- org.eclipse.xtext.generator/packrat/org/eclipse/xtext/generator/parser/packrat/PackratParserGenUtil.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/output/ITreeAppendable.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/scoping/batch/ImplicitlyImportedFeatures.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/scoping/featurecalls/OperatorMapping.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/serializer/XbaseSemanticSequencer.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/ITypeComputationResult.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/ITypeComputationState.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/override/IResolvedFeature.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/util/VarianceInfo.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/IssueCodes.java
> fixed javadoc typos

- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmAnnotationReferenceBuilder.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmAnnotationValueBuilder.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmDeclaredTypeBuilder.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmExecutableBuilder.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmFieldBuilder.java
> use asm 7 experimental towards java 11

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/JvmModelGenerator.xtend
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/compiler/JvmModelGenerator.java
> made generation of error bodies better customizable

- gradle/versions.gradle
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF_gen
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmAnnotationReferenceBuilder.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmAnnotationValueBuilder.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmDeclaredTypeBuilder.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmExecutableBuilder.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmFieldBuilder.java
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/types/TypesGeneratorFragment.java
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
[eclipse/xtext#1325] switch to ASM 7
> [eclipse/xtext#1325] switch to ASM 7

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/XbaseCompiler.java
In order to enable overriding of the functions of `XbaseCompiler`, these two functions must be switched to the `protected` visibility.
> Make protected closeBlock and appendTypeParameters in XbaseCompiler.

- org.eclipse.xtext.xbase.ide/src/org/eclipse/xtext/xbase/ide/contentassist/XbaseIdeCrossrefProposalProvider.xtend
- org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/contentassist/XbaseIdeCrossrefProposalProvider.java
> Set reference kind when we know it should be set

- gradle/versions.gradle
- org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/p2/category.xml
- releng/p2/pom.xml
- releng/pom.xml
- releng/releng-target/pom.xml
> change version 2.16.0 -> 2.17.0

- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/AntlrGrammarComparator.xtend
> fixed warning

- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/impl/DeclaredTypeFactory.java
[eclipse/xtext#1377] set min. asm version to 7
> [eclipse/xtext#1377] set min. asm version to 7

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1283] update to MWE 2.10 M2
> [eclipse/xtext#1283] update to MWE 2.10 M2

- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
[eclipse/xtext#1391] pin guava version to 21
> [eclipse/xtext#1391] pin guava version to 21

- releng/pom.xml
> Set sourceEncoding ISO-8859-1

- org.eclipse.xtext.builder.standalone.tests/.classpath
- org.eclipse.xtext.builder.standalone/.classpath
- org.eclipse.xtext.common.types.tests/.classpath
- org.eclipse.xtext.common.types.tests/xtext.common.types.tests.launch
- org.eclipse.xtext.common.types/.classpath
- org.eclipse.xtext.ecore/.classpath
- org.eclipse.xtext.extras.tests/.classpath
- org.eclipse.xtext.generator/.classpath
- org.eclipse.xtext.java.tests/.classpath
- org.eclipse.xtext.java/.classpath
- org.eclipse.xtext.purexbase.ide/.classpath
- org.eclipse.xtext.purexbase.tests/.classpath
- org.eclipse.xtext.purexbase.tests/xtext.purexbase.tests.launch
- org.eclipse.xtext.purexbase/.classpath
- org.eclipse.xtext.smap/.classpath
- org.eclipse.xtext.xbase.ide/.classpath
- org.eclipse.xtext.xbase.testdata/.classpath
- org.eclipse.xtext.xbase.testing/.classpath
- org.eclipse.xtext.xbase.testlanguages.ide/.classpath
- org.eclipse.xtext.xbase.testlanguages/.classpath
- org.eclipse.xtext.xbase.tests/.classpath
- org.eclipse.xtext.xbase.tests/org.eclipse.xtext.xbase.tests.smoke-suites.launch
- org.eclipse.xtext.xbase.tests/xtext.xbase.tests.fast (xtend).launch
- org.eclipse.xtext.xbase.tests/xtext.xbase.tests.fast.launch
- org.eclipse.xtext.xbase.tests/xtext.xbase.tests.slow (xtend).launch
- org.eclipse.xtext.xbase.tests/xtext.xbase.tests.slow.launch
- org.eclipse.xtext.xbase/.classpath
- org.eclipse.xtext.xbase/GenerateXbase.launch
Changes done by Buildship 3.0.1.v20181217-1554
> [eclipse/xtext#1274] Updated .classpath by Gradle

- org.eclipse.xtext.java.tests/src/org/eclipse/xtext/java/tests/JavaSourceLanguagePerformanceTest.xtend
- org.eclipse.xtext.java.tests/xtend-gen/org/eclipse/xtext/java/tests/JavaSourceLanguagePerformanceTest.java
> timeout experiments on ci.eclipse.org

- gradle/versions.gradle
- org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/p2/category.xml
- releng/p2/pom.xml
- releng/pom.xml
- releng/releng-target/pom.xml
[eclipse/xtext#1414] prepared master for version 2.18.0
> [eclipse/xtext#1414] prepared master for version 2.18.0

- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/bug462047/serializer/Bug462047LangSyntacticSequencer.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/serializer/ContentAssistFragmentTestLangSyntacticSequencer.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/serializer/XImportSectionTestLangSyntacticSequencer.java
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/annotations/serializer/AbstractXbaseWithAnnotationsSyntacticSequencer.java
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/serializer/AbstractXbaseSyntacticSequencer.java
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/serializer/AbstractXtypeSyntacticSequencer.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/serializer/XbaseSyntacticSequencer.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/serializer/XtypeSyntacticSequencer.java
[544435] regenerated test languages
> [544435] regenerated test languages

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/interpreter/impl/XbaseInterpreter.java
made customization of class finder creation more easy
@szarnekow what do you think
cc @hallvard
> made customization of class finder creation more easy

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/interpreter/AbstractConstantExpressionsInterpreter.xtend
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/interpreter/AbstractConstantExpressionsInterpreter.java
mark 'Abstract*' class as abstract
> mark 'Abstract*' class as abstract

- gradle/upstream-repositories.gradle
> replaced tf jenkins with ci.eclipse.org/xtext for lsp4j

- releng/pom.xml
[eclipse/xtext#1422] update to tycho 1.4.0
> [eclipse/xtext#1422] update to tycho 1.4.0

- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF_gen
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/types/TypesGeneratorFragment.java
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/releng-target/xtext-extras.target.target
> [eclipse/xtext#1440] Update to ASM 7.1.0.

- org.eclipse.xtext.java.tests/src/org/eclipse/xtext/java/tests/JavaSourceLanguagePerformanceTest.xtend
- org.eclipse.xtext.java.tests/xtend-gen/org/eclipse/xtext/java/tests/JavaSourceLanguagePerformanceTest.java
[#419] increased timeout as workaround
> [#419] increased timeout as workaround

- CBI.Jenkinsfile
> disable parallel

- 2-maven-build.sh
[eclipse/xtext#1427] disable p2 mirrors
> [eclipse/xtext#1427] disable p2 mirrors

- gradle/versions.gradle
- org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/parser/antlr/XtextAntlrGeneratorComparisonFragment.java
- org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/types/ClasspathScanner.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/compiler/JvmModelGeneratorTest.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/controlflow/ConstantConditionsInterpreter.java
[eclipse/xtext#1437] Bootstrap against 2.18.0.M2
> [eclipse/xtext#1437] Bootstrap against 2.18.0.M2

- org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/LanguageAccessFactory.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/util/AnnotationLookup.java
- org.eclipse.xtext.extras.tests/src/org/eclipse/xtext/tests/AbstractXtextTests.java
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/AntlrDelegatingFragment.java
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/DelegatingGeneratorFragment.java
- org.eclipse.xtext.xbase.testing/deprecated/org/eclipse/xtext/xbase/testing/OnTheFlyJavaCompiler.java
- org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/OnTheFlyJavaCompiler2.xtend
- org.eclipse.xtext.xbase.testing/xtend-gen/org/eclipse/xtext/xbase/testing/OnTheFlyJavaCompiler2.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/jvmmodel/JvmModelCompleter.java
[#425] made code compileable with java 11
> [#425] made code compileable with java 11

- org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/access/impl/AbstractTypeProviderTest.java
- org.eclipse.xtext.java.tests/src/org/eclipse/xtext/common/types/access/impl/AbstractTypeProviderTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/JvmModelGeneratorTest.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/ResolvedOperationTest.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typing/XbaseTypeProviderTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/util/ClasspathScannerTest.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/validation/XbaseValidationTest.xtend
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/compiler/JvmModelGeneratorTest.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/ResolvedOperationTest.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/util/ClasspathScannerTest.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/validation/XbaseValidationTest.java
> [#424] fixed test fails with java 11

- org.eclipse.xtext.xbase.tests/longrunning/src/org/eclipse/xtext/xbase/tests/typesystem/ReturnTypeTests.xtend
- org.eclipse.xtext.xbase.tests/longrunning/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/AbstractReturnTypeTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/AbstractXbaseTestCase.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractClosureTypeTest.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractFeatureCallTypeTest.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractTypeArgumentTest.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractTypeResolverTest.xtend
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/AbstractClosureTypeTest.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/AbstractFeatureCallTypeTest.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/AbstractTypeArgumentTest.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/AbstractTypeResolverTest.java
[#424] fixed longrunning tests with java 11
> [#424] fixed longrunning tests with java 11

- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/AbstractXbaseTestCase.java
> fixed determineJava11OrLater

- Jenkinsfile
https://github.com/eclipse/xtext/issues/1463#issuecomment-498196125
> [eclipse/xtext#1463] Increase timeout to 60 minutes

- gradle/versions.gradle
- org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/p2/category.xml
- releng/p2/pom.xml
- releng/pom.xml
- releng/releng-target/pom.xml
> [eclipse/xtext#1474] Prepare Master for 2.19

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1475] build against orbit 2019-09
> [eclipse/xtext#1475] build against orbit 2019-09

- org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/access/impl/ClasspathTypeProviderTest.java
- org.eclipse.xtext.java.tests/src/org/eclipse/xtext/java/tests/ReusedTypeProviderTest.xtend
> fixed unused imports

- releng/releng-target/xtext-extras.target.target
> [eclipse/xtext#1485] update to mwe 2.11

- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/descriptions/ClasspathScanner.xtend
- org.eclipse.xtext.common.types/xtend-gen/org/eclipse/xtext/common/types/descriptions/ClasspathScanner.java
> performance: cache system classpath in ClasspathScanner

- org.eclipse.xtext.xbase.tests/longrunning/src/org/eclipse/xtext/xbase/tests/typesystem/ReturnTypeTests.xtend
- org.eclipse.xtext.xbase.tests/longrunning/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/AbstractReturnTypeTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/AbstractXbaseTestCase.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractClosureTypeTest.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractConstructorCallTypeTest.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractFeatureCallTypeTest.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractIdentifiableTypeTest.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractTypeArgumentTest.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractTypeResolverTest.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/InvokedResolvedOperationTest.xtend
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typing/XbaseTypeProviderTest.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/AbstractClosureTypeTest.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/AbstractConstructorCallTypeTest.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/AbstractFeatureCallTypeTest.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/AbstractIdentifiableTypeTest.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/AbstractTypeArgumentTest.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/AbstractTypeResolverTest.java
- org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/InvokedResolvedOperationTest.java
made tests runnable with java 12
> made tests runnable with java 12

- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/descriptions/ClasspathScanner.xtend
- org.eclipse.xtext.common.types/xtend-gen/org/eclipse/xtext/common/types/descriptions/ClasspathScanner.java
- releng/releng-target/xtext-extras.target.target
[eclipse/xtext-xtend#818] Add classgraph to target platform
> [eclipse/xtext-xtend#818] Add classgraph to target platform

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/XbaseCompiler.java
[#343] Workaround for NPE in TypeReferenceOwner
> [#343] Workaround for NPE in TypeReferenceOwner

- org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/parser/antlr/AntlrGrammarComparator.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/interpreter/StackedConstantExpressionEvaluationException.java
> regenerate with latest xtend

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/ConstructorLinkingCandidate.java
[#389] Improved overload resolution for ambiguous constructor calls
> [#389] Improved overload resolution for ambiguous constructor calls

- gradle/upstream-repositories.gradle
- releng/pom.xml
> [eclipse/xtext#1507] Adjust lsp4j upstream URL / Use env.JENKINS_URL

- org.eclipse.xtext.java.tests/src/org/eclipse/xtext/java/tests/JavaSourceLanguagePerformanceTest.xtend
- org.eclipse.xtext.java.tests/xtend-gen/org/eclipse/xtext/java/tests/JavaSourceLanguagePerformanceTest.java
> [#419] inc. timeout to 1 min

- releng/pom.xml
use lastStableBuild and not lastSuccessfulBuild
> use lastStableBuild and not lastSuccessfulBuild

- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/adapter/FragmentAdapter.xtend
- org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/adapter/FragmentAdapter.java
> deprecate fragment adapter

- gradle/versions.gradle
- org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/p2/category.xml
- releng/p2/pom.xml
- releng/pom.xml
- releng/releng-target/pom.xml
> [releng] Set version to 2.20.0

- gradle/eclipse-project-layout.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- org.eclipse.xtext.builder.standalone.tests/.classpath
- org.eclipse.xtext.common.types.tests/.classpath
- org.eclipse.xtext.extras.tests/.classpath
- org.eclipse.xtext.java.tests/.classpath
- org.eclipse.xtext.purexbase.tests/.classpath
- org.eclipse.xtext.xbase.tests/.classpath
[eclipse/xtext#1520] update to gradle 5.6.1
> [eclipse/xtext#1520] update to gradle 5.6.1

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1538] use orbit 2019-12
> [eclipse/xtext#1538] use orbit 2019-12

- org.eclipse.xtext.generator/src/org/eclipse/xtext/ui/generator/contentAssist/ContentAssistFragment.xtend
- org.eclipse.xtext.generator/src/org/eclipse/xtext/ui/generator/contentAssist/JavaBasedContentAssistFragment.xpt
- org.eclipse.xtext.generator/src/org/eclipse/xtext/ui/generator/labeling/LabelProviderFragment.xpt
- org.eclipse.xtext.generator/src/org/eclipse/xtext/ui/generator/outline/OutlineTreeProviderFragment.xpt
- org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/ui/generator/contentAssist/ContentAssistFragment.java
> [https://github.com/eclipse/xtext/issues/1556]

- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
[#529759] more consistent bundle names
> [#529759] more consistent bundle names

- releng/pom.xml
[eclipse/xtext#1553] update to tycho 1.5.0
> [eclipse/xtext#1553] update to tycho 1.5.0

- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF_gen
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/types/TypesGeneratorFragment.java
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1567] Upgrade to asm 7.2
> [eclipse/xtext#1567] Upgrade to asm 7.2

- releng/pom.xml
[eclipse/xtext#1566] update to tycho 1.5.1
> [eclipse/xtext#1566] update to tycho 1.5.1

- gradle/wrapper/gradle-wrapper.properties
[eclipse/xtext#1563] update to gradle 5.6.3
> [eclipse/xtext#1563] update to gradle 5.6.3

- org.eclipse.xtext.java/src/org/eclipse/xtext/java/resource/ClassFileCache.xtend
- org.eclipse.xtext.java/xtend-gen/org/eclipse/xtext/java/resource/ClassFileCache.java
[#419] Incorporated review feedback
> [#419] Incorporated review feedback

- org.eclipse.xtext.purexbase/src/org/eclipse/xtext/purexbase/GeneratePureXbase.mwe2
fixed broken config of formatter fragment
> fixed broken config of formatter fragment

- gradle/manifest-gen.gradle
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
[eclipse/xtext#1504] added Eclipse-SourceReferences to manifests
> [eclipse/xtext#1504] added Eclipse-SourceReferences to manifests

- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/build.properties
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/build.properties
moved mwe deps to build.properties
> moved mwe deps to build.properties

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1609] update to mwe 2.11.1
> [eclipse/xtext#1609] update to mwe 2.11.1

- org.eclipse.xtext.common.types.tests/src/org/eclipse/xtext/common/types/xtext/ui/GenerateTypesTestLanguages.mwe2
- org.eclipse.xtext.xbase.testlanguages/src/org/eclipse/xtext/xbase/testlanguages/GenerateXbaseTestLanguages.mwe2
> fixed deprecations

- org.eclipse.xtext.extras.tests/generator/src/org/eclipse/xtext/tests/TestsEMFGeneratorFragment.xtend
- org.eclipse.xtext.extras.tests/generator/xtend-gen/org/eclipse/xtext/tests/TestsEMFGeneratorFragment.java
> avoid unwanted build.properties changes

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/annotations/validation/UnresolvedFeatureCallTypeAwareMessageProvider.xtend
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/annotations/validation/UnresolvedFeatureCallTypeAwareMessageProvider.java
Nothing fancy, just a typo fixed
Signed-off-by: Lorenzo Bettini <lorenzo.bettini@gmail.com>
> recieverType -> receiverType

- gradle/versions.gradle
- org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/p2/category.xml
- releng/p2/pom.xml
- releng/pom.xml
- releng/releng-target/pom.xml
> [releng] Update Xtext version to 2.21.0

- org.eclipse.xtext.java.tests/src/org/eclipse/xtext/java/tests/JavaSourceLanguageTest.xtend
- org.eclipse.xtext.java.tests/xtend-gen/org/eclipse/xtext/java/tests/JavaSourceLanguageTest.java
- org.eclipse.xtext.java/src/org/eclipse/xtext/java/resource/JavaDerivedStateComputer.xtend
- org.eclipse.xtext.java/xtend-gen/org/eclipse/xtext/java/resource/JavaDerivedStateComputer.java
[#538] add special treatment for module and package info on unloading too
> [#538] add special treatment for module and package info on unloading too

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1605] update orbit to 2020-03
> [eclipse/xtext#1605] update orbit to 2020-03

- org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/parser/antlr/AntlrGrammarComparator.java
- org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/contentassist/IIdeTypesProposalProvider.java
- org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/highlighting/XbaseHighlightingStyles.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/controlflow/IConstantEvaluationResult.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/imports/ImportsAcceptor.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/typesystem/arguments/IFeatureCallArgumentSlot.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/typesystem/arguments/IFeatureCallArguments.java
[eclipse/xtext#1642] regenerated xtend code with latest xtend
> [eclipse/xtext#1642] regenerated xtend code with latest xtend

- releng/pom.xml
[eclipse/xtext#1643] update to tycho 1.6.0
> [eclipse/xtext#1643] update to tycho 1.6.0

- org.eclipse.xtext.common.types/build.gradle
> fixed gradle GenerateEMF

- org.eclipse.xtext.purexbase/plugin.xml
- org.eclipse.xtext.purexbase/plugin.xml_gen
- org.eclipse.xtext.xbase.testlanguages/plugin.xml
- org.eclipse.xtext.xbase.testlanguages/plugin.xml_gen
> regenerated test langs

- releng/releng-target/xtext-extras.target.target
> use junit 4.12 explicitely

- releng/releng-target/xtext-extras.target.target
> test with MWE 2.11.2.M3

- org.eclipse.xtext.xbase.testlanguages/src/org/eclipse/xtext/xbase/testlanguages/GenerateXbaseTestLanguages.mwe2
fixed generateXtendStubs for test langs
> fixed generateXtendStubs for test langs

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1673] udpate to MWE 2.11.2
> [eclipse/xtext#1673] udpate to MWE 2.11.2

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/jvmmodel/JvmModelCompleter.java
[eclipse/xtext-xtend#1014] Generate SuppressWarnings for annotations too
> [eclipse/xtext-xtend#1014] Generate SuppressWarnings for annotations too

- gradle/versions.gradle
- org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/p2/category.xml
- releng/p2/pom.xml
- releng/pom.xml
- releng/releng-target/pom.xml
> [releng] Update Xtext version to 2.22.0

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1682] update orbit to 2020-06
> [eclipse/xtext#1682] update orbit to 2020-06

- org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/contentassist/ClasspathBasedIdeTypesProposalProvider.java
- org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/contentassist/XbaseIdeCrossrefProposalProvider.java
regenerated with upstream changes
> regenerated with upstream changes

- org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/adapter/FragmentAdapter.java
> regenerated from upstream

- releng/pom.xml
> [https://github.com/eclipse/xtext/issues/1732] Update to Tycho 1.7.0

- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF_gen
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmAnnotationReferenceBuilder.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmAnnotationValueBuilder.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmDeclaredTypeBuilder.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmExecutableBuilder.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmFieldBuilder.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/impl/DeclaredTypeFactory.java
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/types/TypesGeneratorFragment.java
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1649] update to ASM 8.0
> [eclipse/xtext#1649] update to ASM 8.0

- org.eclipse.xtext.purexbase/src-gen/org/eclipse/xtext/purexbase/parser/antlr/internal/InternalPureXbase.g
- org.eclipse.xtext.purexbase/src-gen/org/eclipse/xtext/purexbase/parser/antlr/internal/InternalPureXbaseParser.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/bug462047/parser/antlr/internal/InternalBug462047Lang.g
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/bug462047/parser/antlr/internal/InternalBug462047LangParser.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/parser/antlr/internal/InternalContentAssistFragmentTestLang.g
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/parser/antlr/internal/InternalContentAssistFragmentTestLangParser.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/parser/antlr/internal/InternalXImportSectionTestLang.g
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/parser/antlr/internal/InternalXImportSectionTestLangParser.java
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/annotations/parser/antlr/internal/InternalXbaseWithAnnotations.g
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/annotations/parser/antlr/internal/InternalXbaseWithAnnotationsParser.java
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/parser/antlr/internal/InternalXbase.g
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/parser/antlr/internal/InternalXbaseParser.java
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/parser/antlr/internal/InternalXtype.g
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/parser/antlr/internal/InternalXtypeParser.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/impl/XAbstractFeatureCallImplCustom.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/linking/XbaseLazyLinker.java
[eclipse/xtext-core#1462] Regenerated languages
> [eclipse/xtext-core#1462] Regenerated languages

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1765] update to MWE 2.11.3.M3
> [eclipse/xtext#1765] update to MWE 2.11.3.M3

- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/impl/DeclaredTypeFactory.java
[eclipse/xtext#1771] fixed asm error message
> [eclipse/xtext#1771] fixed asm error message

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1770] update to mwe 2.11.3 final
> [eclipse/xtext#1770] update to mwe 2.11.3 final

- gradle/versions.gradle
- org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/p2/category.xml
- releng/p2/pom.xml
- releng/pom.xml
- releng/releng-target/pom.xml
> [releng] Update Xtext version to 2.23.0

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1781] update orbit to 2020-09
> [eclipse/xtext#1781] update orbit to 2020-09

- org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/validation/ValidatorFragment.java
- org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/ui/generator/contentAssist/ContentAssistFragment.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/controlflow/EvaluationResult.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting2/ArrayBracketsFormattingReplacer.java
> regenerated with latest aa

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/LogicalContainerAwareReentrantTypeResolver.java
> [#624] Fixed scoping for inner classes

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1816] harmonize includeSource to true in preparation for tycho 2.0
> [eclipse/xtext#1816] harmonize includeSource to true in preparation for tycho 2.0

- gradle/versions.gradle
- org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/p2/category.xml
- releng/p2/pom.xml
- releng/pom.xml
- releng/releng-target/pom.xml
> [releng] Update Xtext version to 2.24.0

- org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/test/XbaseIntegrationTest.java
- org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/test/data/Amount.java
- org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/xbase/junit/evaluation/AbstractXbaseEvaluationTest.java
- org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/evaluation/AbstractXbaseEvaluationTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/junit/evaluation/AbstractXbaseEvaluationTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/conversion/ValueConverterTest.java
fixed warnings when compiling against Java 11
> fixed warnings when compiling against Java 11

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1828] update orbit to 2020-12
> [eclipse/xtext#1828] update orbit to 2020-12

- releng/pom.xml
> use dev bom in tycho build

- Jenkinsfile
archive longrunningTest junit reports
> archive longrunningTest junit reports

- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF_gen
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmAnnotationReferenceBuilder.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmAnnotationValueBuilder.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmDeclaredTypeBuilder.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmExecutableBuilder.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/JvmFieldBuilder.java
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/impl/DeclaredTypeFactory.java
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/types/TypesGeneratorFragment.java
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1852] Update to ASM 9
> [eclipse/xtext#1852] Update to ASM 9

- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/ecore/EMFGeneratorFragment.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/IResolvedTypes.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/references/LightweightTypeReference.java
> fixed javadoc error (Java 11)

- org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/access/impl/AbstractTypeProviderTest.java
- org.eclipse.xtext.java.tests/src/org/eclipse/xtext/common/types/access/impl/AbstractTypeProviderTest.java
> fixed spotbugs bugs

- org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilder.java
- org.eclipse.xtext.extras.tests/src/org/eclipse/xtext/tests/TemporaryFolder.java
- org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/TemporaryFolder.java
> fix temp folder security flaw

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1866] update to MWE(2) 1.6.0/2.12.0 M2
> [eclipse/xtext#1866] update to MWE(2) 1.6.0/2.12.0 M2

- org.eclipse.xtext.xbase/generator/org/eclipse/xtext/xbase/GenerateXbase.java
> fix generateXbase

- releng/releng-target/xtext-extras.target.target
> [releng] Update MWE to 1.6.0/2.12.0

- org.eclipse.xtext.builder.standalone.tests/src-gen/org/eclipse/xtext/builder/tests/services/BuilderTestLanguageGrammarAccess.java
- org.eclipse.xtext.common.types.tests/src-gen/org/eclipse/xtext/common/types/xtext/ui/services/ContentAssistTestLanguageGrammarAccess.java
- org.eclipse.xtext.extras.tests/src-gen/org/eclipse/xtext/generator/grammarAccess/services/GrammarAccessTestLanguageGrammarAccess.java
- org.eclipse.xtext.purexbase/src-gen/org/eclipse/xtext/purexbase/services/PureXbaseGrammarAccess.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/bug462047/services/Bug462047LangGrammarAccess.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/services/ContentAssistFragmentTestLangGrammarAccess.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/services/XImportSectionTestLangGrammarAccess.java
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/annotations/services/XbaseWithAnnotationsGrammarAccess.java
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/services/XbaseGrammarAccess.java
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/services/XtypeGrammarAccess.java
> regenerated languages

- org.eclipse.xtext.extras.tests/src-gen/org/eclipse/xtext/generator/grammarAccess/services/GrammarAccessTestLanguageGrammarAccess.java
- org.eclipse.xtext.purexbase/src-gen/org/eclipse/xtext/purexbase/services/PureXbaseGrammarAccess.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/bug462047/services/Bug462047LangGrammarAccess.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/services/ContentAssistFragmentTestLangGrammarAccess.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/services/XImportSectionTestLangGrammarAccess.java
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/annotations/services/XbaseWithAnnotationsGrammarAccess.java
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/services/XbaseGrammarAccess.java
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/services/XtypeGrammarAccess.java
> regenerated test languages

- gradle/versions.gradle
- org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/p2/category.xml
- releng/p2/pom.xml
- releng/pom.xml
- releng/releng-target/pom.xml
> [releng] Update Xtext version to 2.25.0

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/LogicalContainerAwareReentrantTypeResolver.java
Fixes https://github.com/eclipse/xtext-xtend/issues/1147 in eclipse/xtext-xtend
Signed-off-by: nineninesevenfour <harald.fassler+9974@gmail.com>
> Do not flag serialVersionUID as unused

- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/interpreter/XbaseInterpreterTest.java
test for return; in xbase interpreter
> test for return; in xbase interpreter

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1882][2021-03] Update Orbit
DO NOT merge yet
> [eclipse/xtext#1882][2021-03] Update Orbit

- org.eclipse.xtext.xbase.testdata/src/bar/String.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/ImportManagerTest.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/ImportManager.java
fixes https://github.com/eclipse/xtext-xtend/issues/1029
Signed-off-by: Harald Fassler <harald.fassler+9974@gmail.com>
> avoid unused imports

- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typing/XbaseExpectedTypeProviderTest.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/jvmmodel/IJvmModelInferrer.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/IFeatureLinkingCandidate.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/package-info.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/override/IResolvedExecutable.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/override/IResolvedField.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/override/IResolvedOperation.java
Signed-off-by: miklossy <miklossy@itemis.de>
> Fixing typos in the javadoc comments.

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1925] update to MWE 2.12.1.M2
> [eclipse/xtext#1925] update to MWE 2.12.1.M2

- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF_gen
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/impl/DeclaredTypeFactory.java
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/types/TypesGeneratorFragment.java
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1934] update to ASM 9.1
> [eclipse/xtext#1934] update to ASM 9.1

- gradle/versions.gradle
- org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/p2/category.xml
- releng/p2/pom.xml
- releng/pom.xml
- releng/releng-target/pom.xml
> [releng] Update Xtext version to 2.26.0

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1944] update orbit to 2021-06
> [eclipse/xtext#1944] update orbit to 2021-06

- org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/access/impl/AbstractTypeProviderTest.java
- org.eclipse.xtext.java.tests/src/org/eclipse/xtext/common/types/access/impl/AbstractTypeProviderTest.java
- org.eclipse.xtext.xbase.tests/longrunning/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractReturnTypeTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/AbstractXbaseTestCase.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractTypeResolverTest.java
make tests runnable with java 15 and 16
> make tests runnable with java 15 and 16

- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/MergeableManifest.java
> mark MergeableManifest for removal

- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/controlflow/EvaluationResult.java
regenerated with Xtend 2.26.0.M1
> regenerated with Xtend 2.26.0.M1

- releng/releng-target/xtext-extras.target.target
> update to orbit 2021-09

- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
> use guice 5.0.1

- releng/releng-target/xtext-extras.target.target
> use MWE2 2.12.2.M1

- org.eclipse.xtext.builder.standalone.tests/src-gen/org/eclipse/xtext/builder/tests/serializer/BuilderTestLanguageSemanticSequencer.java
- org.eclipse.xtext.common.types.tests/src-gen/org/eclipse/xtext/common/types/xtext/ui/serializer/ContentAssistTestLanguageSemanticSequencer.java
- org.eclipse.xtext.common.types.tests/src-gen/org/eclipse/xtext/common/types/xtext/ui/serializer/RefactoringTestLanguageSemanticSequencer.java
- org.eclipse.xtext.extras.tests/src-gen/org/eclipse/xtext/enumrules/serializer/EnumAndReferenceTestLanguageSemanticSequencer.java
- org.eclipse.xtext.extras.tests/src-gen/org/eclipse/xtext/enumrules/serializer/EnumRulesTestLanguageSemanticSequencer.java
- org.eclipse.xtext.extras.tests/src-gen/org/eclipse/xtext/enumrules/serializer/MultiRuleEnumTestLanguageSemanticSequencer.java
- org.eclipse.xtext.extras.tests/src-gen/org/eclipse/xtext/generator/grammarAccess/serializer/GrammarAccessTestLanguageSemanticSequencer.java
- org.eclipse.xtext.purexbase/src-gen/org/eclipse/xtext/purexbase/serializer/PureXbaseSemanticSequencer.java
- org.eclipse.xtext.purexbase/src-gen/org/eclipse/xtext/purexbase/serializer/PureXbaseSyntacticSequencer.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/bug462047/serializer/Bug462047LangSemanticSequencer.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/bug462047/serializer/Bug462047LangSyntacticSequencer.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/serializer/ContentAssistFragmentTestLangSemanticSequencer.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/serializer/ContentAssistFragmentTestLangSyntacticSequencer.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/serializer/XImportSectionTestLangSemanticSequencer.java
- org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/serializer/XImportSectionTestLangSyntacticSequencer.java
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/annotations/serializer/AbstractXbaseWithAnnotationsSemanticSequencer.java
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/annotations/serializer/AbstractXbaseWithAnnotationsSyntacticSequencer.java
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/serializer/AbstractXbaseSemanticSequencer.java
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/serializer/AbstractXbaseSyntacticSequencer.java
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/serializer/AbstractXtypeSemanticSequencer.java
- org.eclipse.xtext.xbase/src-gen/org/eclipse/xtext/xbase/serializer/AbstractXtypeSyntacticSequencer.java
[eclipse/xtext-core#1141] regen langs
> [eclipse/xtext-core#1141] regen langs

- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF_gen
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/impl/DeclaredTypeFactory.java
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/types/TypesGeneratorFragment.java
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1978] update to asm 9.2
> [eclipse/xtext#1978] update to asm 9.2

- org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/access/impl/AbstractTypeProviderTest.java
- org.eclipse.xtext.java.tests/src/org/eclipse/xtext/common/types/access/impl/AbstractTypeProviderTest.java
[#723] Fix TypeProvider expectations for Java 17 Enum style
> [#723] Fix TypeProvider expectations for Java 17 Enum style 

- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/AntlrToolFacade.java
[#1522] download via https first and try http on error only in AntlrToolFacade
> [#1522] download via https first and try http on error only in AntlrToolFacade

- Jenkinsfile
[eclipse/xtext#2005] update to maven 3.8.3
> [eclipse/xtext#2005] update to maven 3.8.3

- NOTICE.md
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#2020] update to classgraph 4.8.138
> [eclipse/xtext#2020] update to classgraph 4.8.138

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#2025] update to mwe(2) 1.6.2/2.12.2 release
> eclipse/xtext#2025] update to mwe(2) 1.6.2/2.12.2 release

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#2029] update to orbit 2022-03
> [eclipse/xtext#2029] update to orbit 2022-03

- gradle/versions.gradle
- org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/p2/category.xml
- releng/p2/pom.xml
- releng/pom.xml
- releng/releng-target/pom.xml
> [releng] Update Xtext version to 2.27.0

- org.eclipse.xtext.builder.standalone.tests/test-data/ec-test/test-class/TestClass.java
- org.eclipse.xtext.builder.standalone.tests/test-data/ec-test/test-class2/TestClass2.java
- org.eclipse.xtext.builder.standalone.tests/test-data/standalone/src2/JavaClass.java
- org.eclipse.xtext.extras.tests/src/org/eclipse/xtext/tests/XtextInjectorProvider.java
fixed missing copyright headers
> fixed missing copyright headers

- org.eclipse.xtext.ecore/src/org/eclipse/xtext/ecore/EcoreQualifiedNameProvider.java
> index EEnumLiterals

- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#2028] switch to reload4j
> [eclipse/xtext#2028] switch to reload4j

- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/JvmModelGenerator.xtend
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/output/ITreeAppendable.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/output/SharedAppendableState.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/output/TreeAppendable.java
- org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/compiler/JvmModelGenerator.java
> Lb task 772 avoid empty lines with two spaces

- releng/p2/pom.xml
> bumped maven antrun plugin

- NOTICE.md
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF_gen
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/impl/DeclaredTypeFactory.java
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/types/TypesGeneratorFragment.java
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#2053] Update to ASM 9.3 [eclipse/xtext#2039] Update to Orbit 2022-06
> [eclipse/xtext#2053] Update to ASM 9.3 [eclipse/xtext#2039] Update to Orbit 2022-06

- org.eclipse.xtext.common.types/build.gradle
[eclipse/xtext#2055]simplify dependencies to asm
> [eclipse/xtext#2055]simplify dependencies to asm

- org.eclipse.xtext.common.types.tests/.settings/org.eclipse.xtend.core.Xtend.prefs
- org.eclipse.xtext.extras.tests/.settings/org.eclipse.xtend.core.Xtend.prefs
> cleanup xtend preferences

- gradle/versions.gradle
- org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/p2/category.xml
- releng/p2/pom.xml
- releng/pom.xml
- releng/releng-target/pom.xml
> [releng] Update Xtext version to 2.28.0

- org.eclipse.xtext.builder.standalone.tests/src/org/eclipse/xtext/builder/standalone/TestEclipseCompiler.java
- org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/access/impl/AbstractTypeProviderTest.java
- org.eclipse.xtext.java.tests/src/org/eclipse/xtext/common/types/access/impl/AbstractTypeProviderTest.java
- org.eclipse.xtext.java.tests/src/org/eclipse/xtext/java/tests/JavaSourceLanguageTest.java
- org.eclipse.xtext.xbase.ide/src/org/eclipse/xtext/xbase/ide/contentassist/XbaseIdeContentProposalProvider.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/annotations/ErrorTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/JvmModelGeneratorTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/interpreter/SwitchConstantExpressionsInterpreterTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/jvmmodel/JvmTypeReferenceBuilderTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/jvmmodel/JvmTypesBuilderTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/linking/BeforeLinkingTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/parser/Bug480686Test.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractExpectationTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/ExpressionScopeTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/ResolvedOperationTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/TypeComputationStateTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/validation/ImplicitReturnFinderTest.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/imports/TypeUsageCollector.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/util/ThrownExceptionSwitch.java
fixed spotbugs issues after x2j migration
> fixed spotbugs issues after x2j migration

- org.eclipse.xtext.builder.standalone.tests/src/org/eclipse/xtext/builder/standalone/TestEclipseCompiler.java
switch to java 8 so that ecj is running with annotation proccessing
> switch to java 8 so that ecj is running with annotation proccessing

- NOTICE.md
- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#2071] update to orbit 2022-09
> [eclipse/xtext#2071] update to orbit 2022-09

- gradle/versions.gradle
- org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/p2/category.xml
- releng/p2/pom.xml
- releng/pom.xml
- releng/releng-target/pom.xml
> [releng] Update Xtext version to 2.29.0

- org.eclipse.xtext.builder.standalone.tests/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.xtext.builder.standalone/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.xtext.common.types.tests/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.xtext.common.types/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.xtext.ecore/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.xtext.extras.tests/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.xtext.generator/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.xtext.purexbase/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.xtext.smap/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.xtext.xbase.ide/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.xtext.xbase.testlanguages.ide/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.xtext.xbase.testlanguages/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.xtext.xbase/.settings/org.eclipse.jdt.core.prefs
[eclipse/xtext#2099] added missing org.eclipse.jdt.core.prefs
> [eclipse/xtext#2099] added missing org.eclipse.jdt.core.prefs

- NOTICE.md
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#2089] Update to Orbit 2022-12 incl new classgraph & gson
> [eclipse/xtext#2089] Update to Orbit 2022-12 incl new classgraph & gson

- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/CompilerTest.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/AbstractXbaseCompiler.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/FeatureCallCompiler.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/XbaseCompiler.java
- org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/output/SharedAppendableState.java
> [#806] Fixed NPE in Xbase compiler with broken models

- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
[eclipse/xtext#2103] remove javax.annotation dep. from manifest too
> [eclipse/xtext#2103] remove javax.annotation dep. from manifest too

- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilder.java
[#814] null current source folder for default source folder
[#815] fix MANIFEST.MF and align core.runtime and equinox.common deps with gradle
> Fix Standalone Builder bugs

- org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilder.java
Library resources are not necessarily resolved, validated and updated in the index. Don't log exception when querying their imported names or reference descriptions.
> [#805] Don't log exceptions when serializing the library index

- releng/releng-target/xtext-extras.target.target
> bump tycho bootstrapping

- NOTICE.md
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF_gen
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/impl/DeclaredTypeFactory.java
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/types/TypesGeneratorFragment.java
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#2104] update to asm 9.4
> [eclipse/xtext#2104] update to asm 9.4

- org.eclipse.xtext.xbase.tests/longrunning/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractReturnTypeTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractClosureTypeTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractFeatureCallTypeTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractTypeArgumentTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractTypeResolverTest.java
- org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typing/XbaseTypeProviderTest.java
> clean java 11 guards in tests

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#2106] Update to MWE 2.14.0.M1
> [eclipse/xtext#2106] Update to MWE 2.14.0.M1

- releng/releng-target/xtext-extras.target.target
use fixed asm 9.4 version from orbit m3
> use fixed asm 9.4 version from orbit m3

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#2112] Fix Orbit signing problem
> [eclipse/xtext#2112] Fix Orbit signing problem

- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/MergeableManifest.java
- org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/grammarAccess/UnicodeCharacterDatabaseNames.java
make full use of Java 11 Deprecated annotation
> make full use of Java 11 Deprecated annotation

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#2112] switch back to orbit 2022-12
> [eclipse/xtext#2112] switch back to orbit 2022-12

- gradle/versions.gradle
- org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/p2/category.xml
- releng/p2/pom.xml
- releng/pom.xml
- releng/releng-target/pom.xml
> [releng] Update Xtext version to 2.30.0

- releng/releng-target/xtext-extras.target.target
bootstrap against 2.29 release
> bootstrap against 2.29 release

- org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/InMemoryJavaCompiler.java
> avoid reflection

- org.eclipse.xtext.common.types.tests/src/org/eclipse/xtext/common/types/xtext/ui/GenerateTypesTestLanguages.mwe2
- org.eclipse.xtext.xbase.testlanguages/src/org/eclipse/xtext/xbase/testlanguages/GenerateXbaseTestLanguages.mwe2
> cleanup workflow

- org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/p2/category.xml
- releng/p2/pom.xml
- releng/pom.xml
- releng/releng-target/pom.xml
> [releng] Update Xtext version to 2.28.1

- releng/releng-target/xtext-extras.target.target
[eclipse/xtext#2118] update to orbit 2023-03
> [eclipse/xtext#2118] update to orbit 2023-03

- org.eclipse.xtext.extras.tests/build.gradle
also drop simpleJar from gradle
> also drop simpleJar from gradle

- gradle/versions.gradle
- org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF
- org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
- org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
- org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.generator/META-INF/MANIFEST.MF
- org.eclipse.xtext.java/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF
- org.eclipse.xtext.smap/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
- org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
- releng/p2/category.xml
- releng/p2/pom.xml
- releng/pom.xml
- releng/releng-target/pom.xml
> [releng] Update Xtext version to 2.31.0
