org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/validation/XbaseValidationTest.xtend, org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/validation/XbaseValidationTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/CollectionLiteralsTypeComputer.java
498779: [Xbase] No validation error for #[..] -> Set
Task-Url: https://bugs.eclipse.org/bugs/show_bug.cgi?id=498779
Signed-off-by: Lorenzo Bettini <lorenzo.bettini@gmail.com>
=> 498779: [Xbase] No validation error for #[..] -> Set

org.eclipse.xtext.xbase.testdata/src/interpreter/Foo.java, org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/junit/evaluation/AbstractXbaseEvaluationTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/interpreter/impl/XbaseInterpreter.java
[427166] Allow write access to static fields in xbase interpreter
=> [427166] Allow write access to static fields in xbase interpreter

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/jvmmodel/JvmTypesBuilderTest.xtend, org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/jvmmodel/JvmTypesBuilderTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/jvmmodel/JvmTypesBuilder.java
=> [#48] Escape names in getter/setter when in conflict with Java keywords

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/validation/FeatureCallValidationTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/XbaseConfigurableIssueCodes.java
[401012] Set default Severity for EQUALS_WITH_NULL from ignore to warning
=> [401012] Set default Severity for EQUALS_WITH_NULL from ignore to warning

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/XbaseValidator.java
[403018] Prepare EQUALS_WITH_NULL Issue to be Quickfixable more easy
=> [403018] Prepare EQUALS_WITH_NULL Issue to be Quickfixable more easy

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/serializer/SerializerTest.java
- Expected serialized string adjusted to actual result from the
serializer.
- Extended test to check that the original AST is equal to the one that
gets parsed from the serialized expression.
=> Fixed test

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/resource/BatchLinkableResourceStorageLoadable.xtend, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/resource/BatchLinkableResourceStorageWritable.xtend, org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/resource/BatchLinkableResourceStorageLoadable.java, org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/resource/BatchLinkableResourceStorageWritable.java
used linked maps when storing and loading AssociationsAdapter. Fixes #27
Signed-off-by: Christian Dietrich christian.dietrich@itemis.de
=> used linked maps when storing and loading AssociationsAdapter. Fixes #27

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/CompilerTests2.xtend, org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/validation/XbaseValidationTest.xtend, org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/compiler/CompilerTests2.java, org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/validation/XbaseValidationTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/XbaseTypeComputer.java
It is necessary to also check that, otherwise a return inside a method
that returns a Throwable would be marked as an error.
See https://github.com/eclipse/xtext-xtend/issues/68
Task-Url: https://bugs.eclipse.org/bugs/show_bug.cgi?id=406762
Signed-off-by: Lorenzo Bettini <lorenzo.bettini@gmail.com>
=> 406762: check if the return is contained in a throw

.gitignore, .settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.builder.standalone.tests/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.builder.standalone/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.common.types.tests/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.common.types/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.ecore/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.extras.tests/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.generator/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.java.tests/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.java/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.purexbase.tests/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.purexbase/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.smap/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.xbase.ide/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.xbase.testdata/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.xbase.testing/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.xbase.testlanguages/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.xbase.tests/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.xbase/.settings/org.eclipse.buildship.core.prefs
Files are generated on Gradle project import or by Oomph setup
Ignore org.eclipse.buildship.core.prefs
=> Remove org.eclipse.buildship.core.prefs

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/ReturnTypeTests.xtend, org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/typesystem/AbstractReturnTypeTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/util/ExtendedEarlyExitComputer.java
Added support for switch expressions to the early-exit computer.
currently this works:
`def String foo() {
while(true) {
if(false) return "test"
}
}`
but this fails:
`def String bar() {
while(true) {
switch false {
case true: return "test" 
}
}
}`
with the message "Type mismatch: cannot convert from void to String", this PR fixes this problem
Signed-off-by: Lieven Lemiengre <lieven.lemiengre@sigasi.com>
=> Fixed bug in early-exit validation

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/CompilerTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/FeatureCallCompiler.java
Replacement for https://github.com/eclipse/xtext/pull/1043 after repository split
avoid generation of unnecessary line for getter result
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=492072
Signed-off-by: Karsten Thoms karsten.thoms@itemis.de
=> [492072] Optimized compiler

gradle/p2-deployment.gradle, org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF, releng/releng-target/xtext-extras.target.target
This PR is in line with https://github.com/eclipse/xtext-core/pull/208 and synchronizes `org.eclipse.xtext.xbase.testing`s manifest dependency to `org.junit` with the gradle config.
To that end I had to include `org.junit` from the orbit update site (proxy).
Signed-off-by: Christian Schneider <christian.schneider@typefox.io>
=> [xbase.testing + releng/releng-target] consolidated version of 'org.junit' dependency

build.gradle, gradle/bootstrap-setup.gradle, gradle/eclipse-project-layout.gradle, gradle/xtend-compiler-settings.gradle, org.eclipse.xtext.xbase.tests/build.gradle
* Use build result from xtend-bootstrap job for Xtend compiler
* Added `skipXtendCompiler` option
=> Improve Xtend bootstrap

gradle/versions.gradle, org.eclipse.xtext.builder.standalone.tests/build.gradle, org.eclipse.xtext.builder.standalone/build.gradle, org.eclipse.xtext.common.types.tests/build.gradle, org.eclipse.xtext.generator/build.gradle, org.eclipse.xtext.java/build.gradle, org.eclipse.xtext.purexbase.tests/build.gradle, org.eclipse.xtext.xbase.testing/build.gradle, org.eclipse.xtext.xbase.tests/build.gradle
added explicit dependencies to jdtCompilerApt.
fixes https://github.com/eclipse/xtext-maven/issues/9
=> added explicit dependencies to jdtCompilerApt.

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/imports/ImportOrganizer.java
A usage is local when the declared type is withing the same resource as
the usage context
Fixes the first issue described in https://bugs.eclipse.org/bugs/show_bug.cgi?id=460455
=> [460455] Avoid import of inner classes

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/CompilerTests2.xtend, org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/compiler/CompilerTests2.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/LiteralsCompiler.java
fixed compilation of BigInteger Literals of type 1.23e45 to avoid runtime error. fixes #40
=> fixed compilation of BigInteger Literals of type 1.23e45

org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/impl/AbstractClassMirror.java
findMember: do a full name match first and then the startsWith match. fixes #114
=> findMember: do a full name match first and then the startsWith match

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/JvmModelGeneratorTest.xtend, org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/compiler/JvmModelGeneratorTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/JvmModelGenerator.xtend, org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/compiler/JvmModelGenerator.java
[426073] [xtend][compiler] The generated Java code contains a conflict between a field name and an imported class name
=> [426073] [xtend][compiler] The generated Java code contains a conflict between a field name and an imported class name

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/override/AbstractResolvedOperation.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/override/OverrideHelper.java
[515801] ClassCastException in OverrideHelper.findOverriddenOperation and AbstractResolvedOperation.getOverriddenAndImplementedMethodCandidates
=> [515801] ClassCastException in OverrideHelper.findOverriddenOperation and AbstractResolvedOperation.getOverriddenAndImplementedMethodCandidates

org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
Increased guava version to include version 21.
https://github.com/eclipse/xtext-lib/issues/30
=> Increased guava version to include version 21. 

org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/access/impl/ClasspathTypeProviderTest.java, org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/impl/AbstractRuntimeJvmTypeProvider.java
The elements in the cache might become proxies e.g. if the elements
are unloaded by JvmElementsProxifyingUnloader on
JvmModelAssociator.discardDerivedState(DerivedStateAwareResource)
Returning proxies then will lead to follow up errors as described in #145
=> Do not return cached proxies from typeByQueryString-cache. #145

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/imports/ImportOrganizer.java
Don't do indentity edits during organize imports.
fixes https://github.com/eclipse/xtext-xtend/issues/130
=> Don't do indentity edits during organize imports.

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/jvmmodel/JvmModelAssociaterTest.xtend, org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/jvmmodel/JvmModelAssociaterTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/jvmmodel/JvmModelAssociator.java
JvmModelAssociator removeAssociation does not remove source to jvmElement association #161
=> JvmModelAssociator removeAssociation does not remove source to jvmElement association #161

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/serializer/SerializerTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/serializer/SerializerScopeProvider.java
prefer property syntax over getter syntax
https://github.com/eclipse/xtext-extras/issues/164
=> prefer property syntax over getter syntax

org.eclipse.xtext.java.tests/src/org/eclipse/xtext/java/tests/JavaSourceLanguageTest.xtend, org.eclipse.xtext.java.tests/src/org/eclipse/xtext/java/tests/MySuperClass2.java, org.eclipse.xtext.java.tests/xtend-gen/org/eclipse/xtext/java/tests/JavaSourceLanguageTest.java, org.eclipse.xtext.java/src/org/eclipse/xtext/java/resource/InMemoryClassLoader.xtend, org.eclipse.xtext.java/xtend-gen/org/eclipse/xtext/java/resource/InMemoryClassLoader.java
Fixed issue in impl of InMemoryClassLoader.getResource(String) preventing from name shadowing for types working correct #166
=> Fixed issue in impl of InMemoryClassLoader.getResource(String)

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/imports/RewritableImportSection.java
[473623] Xbase creates Imports when refactoring even if the language has no XImport Section Support
=> [473623] Xbase creates Imports when refactoring even if the language has no XImport Section Support

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/imports/TypeUsageCollector.java
Fix Type Usage Collector for Javadoc with static inner classes
https://github.com/eclipse/xtext-xtend/issues/246
=> Fix Type Usage Collector for Javadoc with static inner classes

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/validation/XbaseValidationTest.xtend, org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/validation/XbaseValidationTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/XbaseValidator.java
fixed check for type guards with generic types in switch expression 
https://github.com/eclipse/xtext-xtend/issues/268
=> fixed check for type guards with generic types in switch expression 

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/resource/BatchLinkableResourceStorageLoadable.xtend, org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/resource/BatchLinkableResourceStorageLoadable.java
Wrap ZipInputStream in a BufferedInputStream before reading from it with
with ObjectInputStream. This improves performance quite significantly
(overall roughly by a factor 4), as the decompression works much more
efficiently with larger chunks of data. See eclipse/xtext-core#481 for
details.
Signed-off-by: Knut Wannheden <knut.wannheden@paranor.ch>
=> Improve performance of BatchLinkableResourceStorageLoadable

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/ConstantInlineExpansionData.java, org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/ConstantInlineExpansionTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/FeatureCallCompiler.java
This PR fixes the invalid generated code when constant inline expressions are invoked.
close #43
Signed-off-by: Stéphane Galland galland@arakhne.org
=> Feature call of constant inline expressions

org.eclipse.xtext.common.types/META-INF/MANIFEST.MF, org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
widened version range for asm to include version 6
https://github.com/eclipse/xtext-core/issues/501
=> widened version range for asm to include version 6

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/AbstractTypeComputer.java
added overloaded (with string as parameter) getTypeForName / getRawTypeForName / findDeclaredType methods #192
=> added overloaded (with string as parameter) getTypeForName / getRawTypeForName / findDeclaredType methods

org.eclipse.xtext.java/src/org/eclipse/xtext/java/resource/JavaDerivedStateComputer.xtend, org.eclipse.xtext.java/xtend-gen/org/eclipse/xtext/java/resource/JavaDerivedStateComputer.java, org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/InMemoryJavaCompiler.xtend, org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/OnTheFlyJavaCompiler.java, org.eclipse.xtext.xbase.testing/xtend-gen/org/eclipse/xtext/xbase/testing/InMemoryJavaCompiler.java
added support for java 9 https://github.com/eclipse/xtext-core/issues/500
=> added support for java 9

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/FeatureScopeTracker.java
made constructor of FeatureScopeTracker public so it can be instantiated more easily by subclasses of OptimizingFeatureScopeTrackerProvider #199
=> made constructor of FeatureScopeTracker public #199

org.eclipse.xtext.purexbase/src/org/eclipse/xtext/purexbase/GeneratePureXbase.mwe2
Excluded EditorFragment2 from Xbase since Xbase already has a manually defined subclass of XtextEditor.
Main part of the fix for [eclipse/xtext-eclipse#463] is in pull request [eclipse/xtext-core#561]
Signed-off-by: Florian Stolte <fstolte@itemis.de>
=> [eclipse/xtext-eclipse#463] Fix for issue

org.eclipse.xtext.purexbase/src/org/eclipse/xtext/purexbase/GeneratePureXbase.mwe2
Adjustments due to the changes in [eclipse/xtext-core#574]:
- removed reference to EditorFragment2 from GeneratePureXbase.mwe2
Signed-off-by: Florian Stolte <fstolte@itemis.de>
=> [eclipse/xtext-eclipse#463] Removed references to EditorFragment2

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/formatting/XbaseFormatterTest.xtend, org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/formatting/XbaseFormatterTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.xtend, org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.java
[528103] fixed issue with formatter and featurecalls inside ()
=> [528103] fixed issue with formatter and featurecalls inside ()

org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.builder.standalone.tests/test-data/model.in.eclipse.project/META-INF/MANIFEST.MF, org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF, org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.common.types/META-INF/MANIFEST.MF, org.eclipse.xtext.ecore/META-INF/MANIFEST.MF, org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.java/META-INF/MANIFEST.MF, org.eclipse.xtext.purexbase.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF, org.eclipse.xtext.smap/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
Signed-off-by: Florian Stolte <fstolte@itemis.de>
=> [eclipse/xtext#1152] Java 9 - Added Automatic-Module-Name header

gradle/p2-deployment.gradle, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/xtext-extras.target.target
- Upgrade to Xtext 2.13
- Upgrade to Tycho 1.1.0
- Use official Orbit
Regenerated pom.xml & target file with generateP2Build task
=> [eclipse/xtext#1170] Update p2-deployment.gradle & derived files

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/validation/ReadWriteAccessTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/XbaseValidator.java
When a JvmField is the left operand of an XAssignment expression, it
should not be considered as used.
=> JvmField is no used when it is assigned.

gradle/upstream-repositories.gradle, org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/junit/evaluation/AbstractXbaseEvaluationTest.java, org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/jvmmodel/CheckExceptionValidationTest.xtend, org.eclipse.xtext.xbase/generator/org/eclipse/xtext/xbase/GenerateXbase.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/TypeConvertingCompiler.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/XbaseCompiler.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/interpreter/impl/XbaseInterpreter.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/XbaseTypeComputer.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/util/ThrownExceptionSwitch.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/IssueCodes.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/JvmTypeReferencesValidator.java
Here we play catch-up with Java by supporting multiple types in catch clauses:
`try { mayThrowException } catch(IllegalArgumentException | IllegalStateException e) { .. }`
We also enable intersection types in switch type guards:
`switch(e) { IllegalArgumentException | IllegalStateException case e.message == 'Whoot': .. }`
=> [411549] Support multicatch and multitype guards in Xtend

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/imports/ConflictResolver.java
- Modify the Xbase ConflictResolver not to fully qualify type names if
two types (one as inner type, one as top-level type) with the same name
exists. In such case, the usage of the fully qualified name is
unnecessary, since the inner type has precedence anyway.
=> [460455] Avoid fully qualifying names when organizing imports.

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/imports/ConflictResolver.java
- Make the OrtanizeImportsTest.tetLocalNameClash test case succeed
again.
=> [#249] Fix failing test cases in the Domain-Model Example.

org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/access/binary/asm/ClassFileBytesAccess.java
This is a hack to be able to work with ASM 6.0 which is not Java 10
compatible. As ASM 6.1 is buggy and ASM 6.1.1 not yet released we check
if the loaded class is compiled with Java 10. If so we modify the major
version byte from 54 (Java 10) to 53 (Java 9). The the byte codes
between both versions are otherwise unchanged this is not critical.
We should remove the hack as soon as ASM 6.1.1 is included in eclipse
and we can remove backwards compatibility with eclipse oxygen 3a and
probabably eclipse photon (depending what ASM version will be shiped
with photon in the end).
=> [eclipse/xtext#1177] HACK: Support java 10 with ASM 6.0

org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF_gen, org.eclipse.xtext.common.types/META-INF/MANIFEST.MF, org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/types/TypesGeneratorFragment.java, org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.purexbase/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
=> [eclipse/xtext#1190] Narrowed the version range for asm to [6.1.1,6.2.0)

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/AbstractClosureTypeHelper.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/XbaseTypeComputer.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/conformance/RawTypeConformanceComputer.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/conformance/TypeConformanceComputationArgument.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/AbstractPendingLinkingCandidate.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/ConstructorLinkingCandidate.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/ResolvedTypes.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/references/LightweightTypeReference.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/util/BoundTypeArgumentMerger.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/util/DeferredTypeParameterHintCollector.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/util/TypeParameterSubstitutor.java
We didn't handle more involving generics situtations properly, e.g. when type constraints referred to type parameters of another nesting level, e.g `T extends A & B, X extends I<T>` where `I<T>`refers to a generic type with complex type constraints, too. During inference, we do now detect situations where we again compare potential type substitutes even though we had seen those before.
The fix is twofold: We figure during the processing of UnboundTypeReferences in the RawTypeConformanceComputer that we did already process a certain reference. The second piece to the puzzle is that we do not collect substitution hints when we know for sure that they are invalid, e.g. when they do not match the type constraints.
This PR also contains minor cosmetic fixes, e.g. for error messages or the …
=> [eclipse/xtext-xtend#461] Avoid stackoverflow in type inferrence

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/validation/JvmTypeReferencesValidatorTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/JvmTypeReferencesValidator.java
[eclipse/xtext-xtend#447] dont issue warnings for raw types inside instanceof
=> [eclipse/xtext-xtend#447] dont issue warnings for raw types inside instanceof

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/formatting/XbaseFormatterTest.xtend, org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/formatting/XbaseFormatterTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.xtend, org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.java
[eclipse/xtext-core#527][eclipse/xtext-xtend#478] fixed issue with conditional formatting
=> [eclipse/xtext-core#527][eclipse/xtext-xtend#478] fixed issue with conditional formatting

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/annotations/typing/XAnnotationUtil.java
Add findAnnotations method to the XAnnotationUtil class to determine all
the JvmAnnotationReferences on a given JvmAnnotationTarget where the
annotations' names are contained in the qualifiedNames set.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=439703
=> [439703] Add findAnnotations method to the XAnnotationUtil class.

org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
- Ensure that the org.eclipse.xtext.xbase.testing package reexports the
require org.eclipse.jdt.core bundle.
=> https://github.com/eclipse/xtext-eclipse/issues/753

org.eclipse.xtext.extras.tests/src/org/eclipse/xtext/generator/CompositeGeneratorFragmentTest.java, org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/test/CompilerTest.xtend, org.eclipse.xtext.purexbase.tests/xtend-gen/org/eclipse/xtext/purexbase/test/CompilerTest.java
=> Fixing typo: 'catched' -> 'caught'

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/imports/TypeUsageCollector.java
[eclipse/xtext-xtend#508] Fixed Type Usage collector for JvmSynonymTypeReferences
=> [eclipse/xtext-xtend#508] Fixed Type Usage collector for JvmSynonymTypeReferences

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/resource/BatchLinkableResource.java
[eclipse/xtext-extras#281] made XtextResource.getEObject(Fragment,Triple) better customizable for BatchLinkableResources
=> [eclipse/xtext-extras#281] made XtextResource.getEObject(Fragment,Triple) better customizable for BatchLinkableResources

org.eclipse.xtext.builder.standalone.tests/src-gen/org/eclipse/xtext/builder/tests/validation/BuilderTestLanguageValidator.java, org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF_gen, org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/bug462047/validation/Bug462047LangValidator.java, org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/validation/ContentAssistFragmentTestLangValidator.java, org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/validation/XImportSectionTestLangValidator.java
[eclipse/xtext#1227] regenerated testlanguages
=> [eclipse/xtext#1227] regenerated testlanguages

org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/evaluation/AbstractXbaseEvaluationTest.java, org.eclipse.xtext.xbase.testing/testdata/testdata/ShorthandNames.java, org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/junit/evaluation/AbstractXbaseEvaluationTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/scoping/batch/AbstractSessionBasedScope.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/serializer/SerializerScopeProvider.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/util/PropertyUtil.xtend, org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/util/PropertyUtil.java
The `SerializerScopeProvider` always calculates the name for extension methods by throwing away the `get` or `is` at the start of the function and then making the first remaining character lowercase. This runs into trouble for methods such as `getURI`. That method's extension name is `URI` not `uRI`.
=> Fixed extension name computation of getters and is-methods in the SerializerScopeProvider

gradle/longrunning-tests.gradle
[eclipse/xtext-extras#168] fixed deprecated gradle api usage for longrunning tests
=> [eclipse/xtext-extras#168] fixed deprecated gradle api usage for longrunning tests

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/DefaultBatchTypeResolver.java
Sometimes, when the JVM model inferrer contains code that leads to a "Cannot root twice", it is helpful to know that is the Eobject that the system tries to root twice times.
This patch add the textual description of the EObject in the error message.
=> Make the "Cannot root twice" error message more explicit

Jenkinsfile, gradle/bootstrap-setup.gradle, gradle/upstream-repositories.gradle, releng/pom.xml
Build steps defined in Jenkinsfile pass the built-in environment
variable 'JENKINS_URL' to the Gradle/Maven executions. This is evaluated
in the build scripts for upstream repository URLs. On Xtext JIPP this
will use upstream repos from JIPP. In local builds outside of Jenkins
the property defaults to Typefox CI like before.
Extend function jenkinsPipelineRepo() by upstreamBranch parameter and use this in the call.
Use jenkinsPipelineRepo() also for lsp4j.
=> [eclipse/xtext#1224] Detect local Jenkins environment

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/JvmModelGenerator.xtend, org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/compiler/JvmModelGenerator.java
Ensure static and final modifiers generated in the right order.
- Modify the JvmModelGenerator to generate the static and the final
modifiers in the right order (corresponding to the java language
specification) 'static final' instead of 'final static'.
=> [https://github.com/eclipse/xtext-xtend/issues/554]

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/CandidateCompareResult.java
It is impossible for the subtypes of `AbstractPendingLinkingCandidate` to call the `compareTo` function because the visibility of `CandidateComparisonResult` is package.
The visiblity should be changed to `public` for enabling the subtypes' functions to call `compareTo`.
=> Change the visibility of CandidateComparisonResult to public.

org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/Generator.java
=> eclipse/xtext-core#864: Use only MergableManifest2 internally.

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/FeatureCallCompiler.java
When the @Inline annotation is used into a Xtend or DSL code, and the
field "constantExpression" is specified into this annotation, the Xbase
compiler fails with a class cast exception.
This issue is due to the fact that the value associated "constantExpression" is not of type
JvmBooleanAnnotationValue, but of type JvmCustomAnnotationValue (with a
XBooleanLiteral inside).
This PR updates the `isConstantExpression` function in order to support both cases.
=> Support JvmCustomAnnotationValue when testing constantExpression.

org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF
=> eclipse-xtext/xtext#1168: Re-export jdt.core (accidently removed).

releng/pom.xml
=> dont adapt jenkinsurl for lsp4j. is not avail. on eclipse ci

org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/ecore/EMFGeneratorFragment.java
[eclipse/xtext-core#967] [Generator] Add option to set GenModel.rootExtendsClass from EMFGeneratorFragment
=> [eclipse/xtext-core#967] [Generator] Add option to set GenModel.rootExtendsClass from EMFGeneratorFragment

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/JavaKeywordTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/JavaKeywords.java
- Delegate to javax.lang.model.SourceVersion.isKeyword(String s) method.
- Implement additional JavaKeywordTest test cases.
=> [#346] Refactoring the JavaKeywords.isJavaKeyword(String s) method.

org.eclipse.xtext.java.tests/build.gradle
[eclipse/xtext#1182] added support for java 11 as target
=> [eclipse/xtext#1182] added support for java 11 as target

releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1283] update to MWE 2.10
do not merge before mwe 2.10.0 final is out
=> [eclipse/xtext#1283] update to MWE 2.10

gradle/upstream-repositories.gradle
=> workaround for jcenter maven central sync is too slow

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/CompilerTests2.xtend, org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/compiler/CompilerTests2.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/FeatureCallCompiler.java
[#394][eclipse/xtext-lib#60] fixed issues with nested inline feature calls
=> [#394][eclipse/xtext-lib#60] fixed issues with nested inline feature calls

1-gradle-build.sh, 2-maven-build.sh, 3-gradle-longrunning-tests.sh, CBI.Jenkinsfile, releng/pom.xml
- externalized build steps into shell scripts for convenient local usage
- added Slack notifications
- configure Maven default goal
- parallelize Maven build and long-running tests
=> [eclipse/xtext#1309] Provide Jenkinsfile for Eclipse CBI

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/TypeConvertingCompiler.java
In order to allow overriding, the functions `convertWrapperToPrimitive()` and `convertPrimitiveToWrapper()` should have a protected accessibility.
=> Protected visibility for convertWrapperToPrimitive() and convertPrimitiveToWrapper()

org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/test/PureXbaseInterpreterTest.xtend, org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/test/XbaseIntegrationTest.java, org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/xbase/junit/evaluation/AbstractXbaseEvaluationTest.java, org.eclipse.xtext.purexbase.tests/xtend-gen/org/eclipse/xtext/purexbase/test/PureXbaseInterpreterTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/XbaseCompiler.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/interpreter/impl/XbaseInterpreter.java
Invoke all close methods from resources in try-with-resources and
propagate thrown exceptions afterwards for the Java6-style code generator and for the interpreter.
Signed-off-by: Max Leuthäuser <max.leuthaeuser@itemis.de>
=> [eclipse/xtext-extras#415] Improve exception handling for try-with-resource

CBI.Jenkinsfile
CBI.Jenkinsfile should be updated as well
https://github.com/eclipse/xtext/issues/1463#issuecomment-498196125
=> [eclipse/xtext#1463] Increase timeout to 60 minutes

org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/access/impl/AbstractTypeProviderTest.java, org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/access/impl/ClasspathTypeProviderTest.java, org.eclipse.xtext.common.types/META-INF/MANIFEST.MF, org.eclipse.xtext.java.tests/src/org/eclipse/xtext/java/tests/ReusedTypeProviderTest.xtend, org.eclipse.xtext.java.tests/xtend-gen/org/eclipse/xtext/java/tests/ReusedTypeProviderTest.java, releng/releng-target/xtext-extras.target.target
Fixes eclipse/xtext#1398 and eclipse/xtext-lib#111
=> update to guava 27.1

Jenkinsfile
=> [eclipse/xtext#1481] Delete org/eclipse/[xtext|xtend] from local .m2

1-gradle-build.sh, 3-gradle-longrunning-tests.sh, CBI.Jenkinsfile
Disable Gradle daemon, since a new container for each build is
spawned and the daemon can't be reused anyway.
Remove CPU resource constraint, since default is sufficient.
=> [eclipse/xtext#1431] Enhance container support

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/AbstractXbaseCompiler.java
[eclipse/xtext-xtend#831] added missing overide for closure anonymous class
=> [eclipse/xtext-xtend#831] added missing override for closure anonymous class

org.eclipse.xtext.extras.tests/src/org/eclipse/xtext/tests/TemporaryFolder.java, org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/TemporaryFolder.java
[eclipse/xtext#1432] fixed implementation of TemporaryFolder.createTempFile
=> [eclipse/xtext#1432] fixed implementation of TemporaryFolder.createTempFile

releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1279] use orbit simrel alias directly
=> [eclipse/xtext#1279] use orbit simrel alias directly

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/scoping/batch/NestedTypesScope.java
[eclipse/xtext-xtend#897] fixed problem with constructors and nested types
=> [eclipse/xtext-xtend#897] fixed problem with constructors and nested types

org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/ex/ExternalAntlrLexerFragment.java, org.eclipse.xtext.xbase.testlanguages/src-gen/org/eclipse/xtext/xbase/testlanguages/services/ContentAssistFragmentTestLangGrammarAccess.java
[eclipse/xtext-eclipse#1161] ExternalAntlrLexerFragment produces consistent output
=> [eclipse/xtext-eclipse#1161] ExternalAntlrLexerFragment produces consistent output

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.xtend, org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.java
[eclipse/xtext-eclipse#1220] fixed formatting of arraybrackets
=> [eclipse/xtext-eclipse#1220] fixed formatting of arraybrackets

org.eclipse.xtext.java/src/org/eclipse/xtext/java/resource/ClassFileCache.xtend, org.eclipse.xtext.java/src/org/eclipse/xtext/java/resource/JavaDerivedStateComputer.xtend, org.eclipse.xtext.java/xtend-gen/org/eclipse/xtext/java/resource/ClassFileCache.java, org.eclipse.xtext.java/xtend-gen/org/eclipse/xtext/java/resource/JavaDerivedStateComputer.java
[#419] Improve performance of Java source language
The patch is based on batched compilation of Java source files. Most of the time for the Java source language is eaten up by repetitive compilation of referenced Java files, if we compile each Java source file individually.
This is changed towards a queue of not-yet-compiled, fully installed Java source resources. As soon as a resource is compiled, it compiles all of its friends and caches the result. A subsequent request to fully install Java source resource contents will first consult the cache and reuse the available cached data, if any.
=> [#419] Improve performance of Java source language

org.eclipse.xtext.common.types.tests/xtext.common.types.tests.launch, org.eclipse.xtext.purexbase.tests/xtext.purexbase.tests.launch, org.eclipse.xtext.xbase.tests/org.eclipse.xtext.xbase.tests.smoke-suites.launch, org.eclipse.xtext.xbase.tests/xtext.xbase.tests.fast (xtend).launch, org.eclipse.xtext.xbase.tests/xtext.xbase.tests.fast.launch, org.eclipse.xtext.xbase.tests/xtext.xbase.tests.slow (xtend).launch, org.eclipse.xtext.xbase.tests/xtext.xbase.tests.slow.launch, org.eclipse.xtext.xbase/GenerateXbase.launch
These changes were automatically applied to the launch configurations on
a fresh workspace setup.
=> [eclipse/xtext#1568] Remove Buildship classpath container

org.eclipse.xtext.ecore/META-INF/MANIFEST.MF
[#540] Re-export org.eclipse.xtext to not break downstream projects
closes #540
=> [#540] Re-export org.eclipse.xtext to not break downstream projects

org.eclipse.xtext.java/src/org/eclipse/xtext/java/resource/JavaDerivedStateComputer.xtend
[#544] workaround: set explicit return types to avoid object as return type issue
=> [#544] workaround: set explicit return types to avoid object as return type issue

org.eclipse.xtext.purexbase.ide/src-gen/org/eclipse/xtext/purexbase/ide/contentassist/antlr/PartialPureXbaseContentAssistParser.java
[eclipse/xtext-core#1418] removed redundant superinterface from generated ca parsers
=> [eclipse/xtext-core#1418] removed redundant superinterface from generated ca parsers

org.eclipse.xtext.extras.tests/deprecated/org/eclipse/xtext/generator/grammarAccess/UnicodeCharacterDatabaseNamesTest.java, org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/grammarAccess/GrammarAccessUtil.java, org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/grammarAccess/UnicodeCharacterDatabaseNames.java
[eclipse/xtext#1738] avoid usage of icu.Transliterator
=> [eclipse/xtext#1738] avoid usage of icu.Transliterator

org.eclipse.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.purexbase/build.properties, org.eclipse.xtext.xbase/META-INF/MANIFEST.MF
[eclipse/xtext#1738] removed no longer needed icu dependency
=> [eclipse/xtext#1738] removed no longer needed icu dependency

org.eclipse.xtext.xbase.testlanguages/src/org/eclipse/xtext/xbase/testlanguages/GenerateXbaseTestLanguages.mwe2
=> GenerateXbaseTestLanguages: setting the generateEclipse flag to true.

Jenkinsfile
This should be a no-op for the build but it makes build jobs more independant from infrastructure changes / issues like https://bugs.eclipse.org/bugs/show_bug.cgi?id=563024.
Linked to eclipse/xtext#1769
Signed-off-by: Mikaël Barbero <mikael.barbero@eclipse-foundation.org>
=> Removed jnlp image name from pod template

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/override/OverrideTester.java
[eclipse/xtext-xtend#1035] Missing validation in context of static interface methods
=> [eclipse/xtext-xtend#1035] Missing validation in context of static interface methods

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/TypeConvertingCompiler.java
The visibility of the function doCastConversion() in
TypeConvertingCompiler is increased to protected in order
to enable its call from the sub-types.
=> [xbase] Protected visibility for doCastConversion().

org.eclipse.xtext.builder.standalone/.settings/org.eclipse.xtend.shared.ui.prefs, org.eclipse.xtext.common.types.tests/.settings/org.eclipse.xtend.shared.ui.prefs, org.eclipse.xtext.common.types/.settings/org.eclipse.xtend.shared.ui.prefs, org.eclipse.xtext.extras.tests/.settings/org.eclipse.xtend.shared.ui.prefs, org.eclipse.xtext.generator/.settings/org.eclipse.xtend.shared.ui.prefs
removed obsolete org.eclipse.xtend.shared.ui.prefs
=> removed obsolete org.eclipse.xtend.shared.ui.prefs

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/interpreter/impl/XbaseInterpreter.java
Evaluating the following example with `XbaseInterpreter` yields an internal error:
```
def void foo(){
return
}
def String bar(){
foo();
"bla"
}
bar()
```
The error is only shown in the console. The relevant stacktrace section is:
```
Caused by: java.lang.IllegalArgumentException: Unhandled parameter types: [null, org.eclipse.xtext.xbase.interpreter.impl.DefaultEvaluationContext@3a687ba6, org.eclipse.xtext.builder.MonitorBasedCancelIndicator@7f6af28f]
at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:271)
at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:204)
at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:285)
at …
```
=> bugfix 'return void' in XbaseInterpreter

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/interpreter/impl/XbaseInterpreter.java
[eclipse/xtext#1923] Change visibility
of the XbaseInterpreter.ReturnValue class from package private to
public.
Signed-off-by: miklossy <miklossy@itemis.de>
=> [eclipse/xtext#1923] Change visibility

org.eclipse.xtext.common.types/META-INF/MANIFEST.MF, releng/releng-target/xtext-extras.target.target
Update Google Guava version from 27.1.0 to 30.1.0
Signed-off-by: miklossy <miklossy@itemis.de>
=> https://github.com/eclipse/xtext/issues/1862 Guava 30.1.0

releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1928] Bootstrap against MWE(2) 1.6.1/2.12.1 Final
=> [eclipse/xtext#1928] Bootstrap against MWE(2) 1.6.1/2.12.1 Final

releng/releng-target/xtext-extras.target.target
[eclipse/xtext#1927] re-adjust bootstrapping targets for mwe(2)
=> [eclipse/xtext#1927] re-adjust bootstrapping targets for mwe(2)

org.eclipse.xtext.common.types/emf-gen/org/eclipse/xtext/common/types/JvmMember.java, org.eclipse.xtext.common.types/emf-gen/org/eclipse/xtext/common/types/impl/JvmMemberImpl.java, org.eclipse.xtext.common.types/emf-gen/org/eclipse/xtext/common/types/impl/TypesPackageImpl.java, org.eclipse.xtext.common.types/model/JavaVMTypes.ecore
[eclipse/xtext-extras#704] mark JvmMember.identifier non derived + settable
=> [eclipse/xtext-extras#704] mark JvmMember.identifier non derived + settable

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/jvmmodel/JvmModelAssociator.java
[eclipse/xtext-extras#695] fix removeAssociation leaving orphans in target2source map
=> [eclipse/xtext-extras#695] fix removeAssociation leaving orphans in target2source map

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/XbaseCompiler.java
[eclipse/xtext-xtend#1301] fix name clashes with anony. inner classes
=> [eclipse/xtext-xtend#1301] fix name clashes with anony. inner classes

org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilder.java
The StandaloneBuilder is supposed to validate all resources and fail only afterwards (before generation).
The behavior is not consistent with clustering enabled, but it restores the previous state.
See #805 
=> [#805] Fixed accidentally broken semantic of failOnValidationError

org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilder.java
If explicit javaSourceDirs are present, only consider these and the stub generation directory when stubs are being compiled.
=> [#805] Don't blindly compile all source directories

org.eclipse.xtext.builder.standalone.tests/src/org/eclipse/xtext/builder/standalone/TestEclipseCompiler.java, org.eclipse.xtext.builder.standalone.tests/src/org/eclipse/xtext/builder/standalone/TestIncrementalEclipseCompiler.java, org.eclipse.xtext.builder.standalone.tests/test-data/ec-test/test-class3/com/acme/Tweety.java, org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilder.java, org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilderFileCallback.java, org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/compiler/InternalIncrementalCompiler.java, org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/compiler/SerializedCompilerState.java, org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/incremental/BinaryFileHashing.java, org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/incremental/ClasspathEntryHash.java, org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/incremental/ClasspathEntryHashVisitor.java, org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/incremental/ClasspathInfos.java, org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/incremental/CoarseGrainedEntryHash.java, org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/incremental/FineGrainedEntryHash.java
This avoids a full build for the test sources if the production source code of a maven project is changed. Only the affected tests / models will need to be recompiled
[eclipse/xtext-extras#805]
=> [#805] Incremental compilation: Use fine grained hash for class files

org.eclipse.xtext.ecore/src/org/eclipse/xtext/ecore/EcoreQualifiedNameProvider.java
This way, one can simply redefine the default implementation instead of single cases.
Signed-off-by: Lorenzo Bettini <lorenzo.bettini@gmail.com>
=> provide a default implementation using ENamedElement.getName

org.eclipse.xtext.builder.standalone.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF_gen, org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/junit/Junit4Fragment.java, org.eclipse.xtext.java.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.testdata/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.xbase.tests/META-INF/MANIFEST.MF
[eclipse/xtext#2125] set minimum junit version to 4.13.2
=> [eclipse/xtext#2125] set minimum junit version to 4.13.2

org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/typesystem/AbstractTypeResolverTest.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/IResolvedTypes.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/ITypeComputationState.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/AbstractTypeComputationState.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/ExpressionAwareStackedResolvedTypes.java, org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/ResolvedTypes.java
Deep Xbase expression trees could easily lead to a frozen editor due to the complexity of the type resolution.
By reusing previous computation results and therefore avoiding duplicate work, the performance could be greatly improved.
=> [eclipse/xtext-xtend#1005] Improve linking performance
